name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/download-artifact@master
      with: 
        name: database-proj-task2-2019.11-jar-with-dependencies.jar
        path: target
      
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Maven
      run: mvn package | cat target/database-proj-task2-2019.11-jar-with-dependencies.jar

      
  #  - run: cat target/database-proj-task2-2019.11-jar-with-dependencies.jar
      
